services:
  postgres:
    image: postgres:15-alpine
    container_name: music-streaming-db-java
    environment:
      POSTGRES_DB: musicdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_java:/var/lib/postgresql/data
    networks:
      - music-network-java

  app:
    build: .
    container_name: music-streaming-app-java
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/musicdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    ports:
      - "8081:8080"
      - "9091:9090"
    networks:
      - music-network-java

volumes:
  postgres_data_java:

networks:
  music-network-java:
    driver: bridge
